### PR TITLE
Downgrade to v0.1.91, set build number to 5

### PR DESCRIPTION
**Pull request by setu4993**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by setu4993** [comment]
@BastianZim : Looks like the OS X build for v0.1.91 is failing as it was in #5.

**Comment by BastianZim** [comment]
@setu4993 Ahh shame, ok then I'll talk to the upstream repo where I'd need this, maybe they can relax their restrictions. Thanks for your help anyways!

**Comment by BastianZim** [comment]
I think this comes from here which was only fixed after .91 https://github.com/google/sentencepiece/issues/583 but not 100% sure.

**Comment by BastianZim** [comment]
Just to clarify, feel free to close the PR. I'll see if the upstream repo accepts a newer version and otherwise, I'll try to fix this locally and will submit a PR if successful.

**Comment by setu4993** [comment]
Thanks @BastianZim, TBH not sure what causes it. Going to close this for now and can revisit alternatives if it becomes absolutely necessary.

**Comment by BastianZim** [comment]
Thanks @setu4993!

**Pull request closed without merging**
