### PR TITLE
WIP: Try to build lib separately

### PR DESCRIPTION
**Pull request by h-vetinari**
Towards #25

### CODE REVIEW

**Comment by h-vetinari** [comment]
looking for `_i_give_permission_to_break_this_code_default_unk_piece_` seems to produce a lead: https://github.com/google/sentencepiece/issues/593

**Comment by h-vetinari** [comment]
.... or not. The mentioned [`test.bat`](https://github.com/google/sentencepiece/blob/master/test.bat) just builds static libraries... 😑

**Comment by h-vetinari** [comment]
Really starting to wonder if it's worth the effort to build a shared lib for windows. The upstream situation is just such an impenetrable mix of libraries, vendoring and custom glue code that I'm really struggling.

**Comment by h-vetinari** [comment]
Ah, it seems they should be coming from [here](https://github.com/google/sentencepiece/blob/v0.1.96/src/builtin_pb/sentencepiece_model.pb.h#L939) using `GOOGLE_PROTOBUF_EXTENSION_ACCESSORS`, which doesn't seem to be working on windows. Every come across this @xhochy?

**Comment by h-vetinari** [comment]
Any experience with `GOOGLE_PROTOBUF_EXTENSION_ACCESSORS` (+win) @xhochy?

**Comment by xhochy** [comment]
No, never had to deal with them. Do you know where that macro is defined? I have a hard time googling for it.

**Comment by h-vetinari** [comment]
> No, never had to deal with them. Do you know where that macro is defined? I have a hard time googling for it.

Found the [definition](https://github.com/google/sentencepiece/blob/v0.1.96/third_party/protobuf-lite/google/protobuf/extension_set.h#L1382-L1551) in the sentence-piece third party sources. It's pretty big...

**Comment by h-vetinari** [comment]
@xhochy
Nothing particularly windows-specific stands out to me in the definition of `GOOGLE_PROTOBUF_EXTENSION_ACCESSORS` (link above) - any ideas?

**Comment by xhochy** [comment]
> Really starting to wonder if it's worth the effort to build a shared lib for windows. The upstream situation is just such an impenetrable mix of libraries, vendoring and custom glue code that I'm really struggling to debug some very cryptic errors.

Going through the logs again, I would say no. Seems like the GOOGLE_PROTOBUF_EXTENSION_ACCESSORS won't be the only hurdle.

**Comment by xhochy** [comment]
Did you try building here with the EXPORT_ALL_SYMBOLS flag on?

**Comment by h-vetinari** [comment]
> Did you try building here with the EXPORT_ALL_SYMBOLS flag on?

Did that now and it then fails at a different point:
```
spm_decode_main.obj : error LNK2019: unresolved external symbol "class absl::Flag<int> FLAGS_minloglevel" (?FLAGS_minloglevel@@3V?$Flag@H@absl@@A) referenced in function main [D:\bld\sentencepiece-split_1640913561144\work\build\src\spm_decode.vcxproj]
```

I've found the following [snippet](https://github.com/google/sentencepiece/blob/v0.1.96/src/error.cc#L20-L27) upstream
```C
#ifdef _USE_EXTERNAL_ABSL
// Naive workaround to define minloglevel on external absl package.
// We want to define them in other cc file.
#include "third_party/absl/flags/flag.h"
#include "third_party/absl/flags/parse.h"
ABSL_FLAG(int32, minloglevel, 0,
          "Messages logged at a lower level than this don't actually.");
#endif
```

but even setting `_USE_EXTERNAL_ABSL` didn't help. Interestingly, that guard isn't used [elsewhere](https://github.com/google/sentencepiece/blob/v0.1.96/src/init.h). 

The relevant abseil-macros (`ABSL_FLAG` / `ABSL_DECLARE_FLAG`) are actually what is [recommended](https://github.com/abseil/abseil-cpp/blob/20211102.0/absl/flags/flag.h#L23-L27) usage by abseil, but it [looks like](https://github.com/google/sentencepiece/blob/v0.1.96/third_party/absl/flags/flag.h#L57-L60) sentencepiece (p)redeclares them.

**Comment by h-vetinari** [comment]
Nevermind, the flags things is a bit of a red herring at the moment; I hadn't noticed that it still runs into
```
     Creating library D:/bld/sentencepiece-split_1640913561144/work/build/src/Release/sentencepiece_train_import.lib and object D:/bld/sentencepiece-split_1640913561144/work/build/src/Release/sentencepiece_train_import.exp
trainer_interface.obj : error LNK2019: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_unk_piece_" (?_i_give_permission_to_break_this_code_default_unk_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) referenced in function "public: bool __cdecl <lambda_e29d05afb1d6eeb86afbc2647f25bd32>::operator()(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum sentencepiece::ModelProto_SentencePiece_Type)const " (??R<lambda_e29d05afb1d6eeb86afbc2647f25bd32>@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ModelProto_SentencePiece_Type@sentencepiece@@@Z) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2001: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_unk_piece_" (?_i_give_permission_to_break_this_code_default_unk_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
trainer_interface.obj : error LNK2019: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_bos_piece_" (?_i_give_permission_to_break_this_code_default_bos_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) referenced in function "public: bool __cdecl <lambda_e29d05afb1d6eeb86afbc2647f25bd32>::operator()(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum sentencepiece::ModelProto_SentencePiece_Type)const " (??R<lambda_e29d05afb1d6eeb86afbc2647f25bd32>@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ModelProto_SentencePiece_Type@sentencepiece@@@Z) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2001: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_bos_piece_" (?_i_give_permission_to_break_this_code_default_bos_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
trainer_interface.obj : error LNK2019: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_eos_piece_" (?_i_give_permission_to_break_this_code_default_eos_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) referenced in function "public: bool __cdecl <lambda_e29d05afb1d6eeb86afbc2647f25bd32>::operator()(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum sentencepiece::ModelProto_SentencePiece_Type)const " (??R<lambda_e29d05afb1d6eeb86afbc2647f25bd32>@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ModelProto_SentencePiece_Type@sentencepiece@@@Z) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2001: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_eos_piece_" (?_i_give_permission_to_break_this_code_default_eos_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
trainer_interface.obj : error LNK2019: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_pad_piece_" (?_i_give_permission_to_break_this_code_default_pad_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl sentencepiece::TrainerSpec::pad_piece(void)const " (?pad_piece@TrainerSpec@sentencepiece@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2001: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_pad_piece_" (?_i_give_permission_to_break_this_code_default_pad_piece_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
trainer_interface.obj : error LNK2019: unresolved external symbol "const sentencepiece::ModelProto::`vftable'" (??_7ModelProto@sentencepiece@@6B@) referenced in function "private: class sentencepiece::util::Status __cdecl sentencepiece::TrainerInterface::SaveModel(class absl::string_view)const " (?SaveModel@TrainerInterface@sentencepiece@@AEBA?AVStatus@util@2@Vstring_view@absl@@@Z) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
unigram_model_trainer.obj : error LNK2001: unresolved external symbol "const sentencepiece::ModelProto::`vftable'" (??_7ModelProto@sentencepiece@@6B@) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2001: unresolved external symbol "const sentencepiece::ModelProto::`vftable'" (??_7ModelProto@sentencepiece@@6B@) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
unigram_model_trainer.obj : error LNK2019: unresolved external symbol "struct sentencepiece::TrainerSpecDefaultTypeInternal sentencepiece::_TrainerSpec_default_instance_" (?_TrainerSpec_default_instance_@sentencepiece@@3UTrainerSpecDefaultTypeInternal@1@A) referenced in function "public: virtual bool __cdecl sentencepiece::ModelInterface::ByteFallbackEnabled(void)const " (?ByteFallbackEnabled@ModelInterface@sentencepiece@@UEBA_NXZ) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2019: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_unk_surface_" (?_i_give_permission_to_break_this_code_default_unk_surface_@TrainerSpec@sentencepiece@@0VLazyString@internal@protobuf@google@@B) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl sentencepiece::PrintProto(class sentencepiece::TrainerSpec const &,class absl::string_view)" (?PrintProto@sentencepiece@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVTrainerSpec@1@Vstring_view@absl@@@Z) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2019: unresolved external symbol "const sentencepiece::TrainerSpec::`vftable'" (??_7TrainerSpec@sentencepiece@@6B@) referenced in function "public: static class sentencepiece::util::Status __cdecl sentencepiece::SentencePieceTrainer::Train(class std::unordered_map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::hash<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,struct std::equal_to<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &,class sentencepiece::SentenceIterator *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?Train@SentencePieceTrainer@sentencepiece@@SA?AVStatus@util@2@AEBV?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@std@@PEAVSentenceIterator@2@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@6@@Z) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2019: unresolved external symbol "const sentencepiece::NormalizerSpec::`vftable'" (??_7NormalizerSpec@sentencepiece@@6B@) referenced in function "public: static class sentencepiece::NormalizerSpec __cdecl sentencepiece::SentencePieceTrainer::GetNormalizerSpec(class absl::string_view)" (?GetNormalizerSpec@SentencePieceTrainer@sentencepiece@@SA?AVNormalizerSpec@2@Vstring_view@absl@@@Z) [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
D:\bld\sentencepiece-split_1640913561144\work\build\src\Release\sentencepiece_train.dll : fatal error LNK1120: 9 unresolved externals [D:\bld\sentencepiece-split_1640913561144\work\build\src\sentencepiece_train.vcxproj]
```

**Comment by h-vetinari** [comment]
I think I'm coming full circle to the idea that (e.g. for `GOOGLE_PROTOBUF_EXTENSION_ACCESSORS` to work) we're probably gonna need https://github.com/conda-forge/libprotobuf-feedstock/pull/100 for protobuf.

**Comment by h-vetinari** [comment]
> Nothing particularly windows-specific stands out to me in the definition of `GOOGLE_PROTOBUF_EXTENSION_ACCESSORS` (link above) - any ideas?

Well, one big reason is that libprotobuf 3.18.0 [removed](https://github.com/protocolbuffers/protobuf/commit/562fc946c748d0ddb451ad1ce48570685f23a4f1) that macro, but then I still don't understand why linux/osx manage to get through...

**Comment by h-vetinari** [comment]
I noticed that all the problematic ones were `static const` [here](https://github.com/google/sentencepiece/blob/v0.1.96/src/builtin_pb/sentencepiece_model.pb.h#L958-L966). Feels like [this](https://stackoverflow.com/questions/16049306/error-lnk2001-unresolved-external-symbol-private-static-class) might have something to do with it.

**Comment by h-vetinari** [comment]
@xhochy

> I noticed that all the problematic ones were `static const` [here](https://github.com/google/sentencepiece/blob/v0.1.96/src/builtin_pb/sentencepiece_model.pb.h#L958-L966). [...might be related to] better [link](https://isocpp.org/wiki/faq/ctors#link-errs-static-data-mems)

So, from what I can see the static data members are correctly [defined](https://github.com/google/sentencepiece/blob/v0.1.96/src/builtin_pb/sentencepiece_model.pb.cc#L394-L398) in exactly one translation unit, but something seems to be messing with the initialisation of [`LazyString`](https://github.com/google/sentencepiece/blob/v0.1.96/third_party/protobuf-lite/google/protobuf/arenastring.h#L56-L85).

Notably, this class has no explicit constructor, and - I admit I'm fully out of my depth here - the definition seems to do [brace initialisation](https://docs.microsoft.com/en-us/cpp/cpp/initializing-classes-and-structs-without-constructors-cpp?view=msvc-170) of a union of structs. Could it be that this somehow doesn't work correctly (in combination with static) on MSVC?

<details>
<summary>occurrences of <code>LazyString</code> in sentencepiece sources</summary>

```
>findstr /L /S /N "LazyString" *.*
src\builtin_pb\sentencepiece_model.pb.cc:394:const ::PROTOBUF_NAMESPACE_ID::internal::LazyString TrainerSpec::_i_give_permission_to_break_this_code_default_unk_piece_{{{"<unk>", 5}}, {nullptr}};
src\builtin_pb\sentencepiece_model.pb.cc:395:const ::PROTOBUF_NAMESPACE_ID::internal::LazyString TrainerSpec::_i_give_permission_to_break_this_code_default_bos_piece_{{{"<s>", 3}}, {nullptr}};
src\builtin_pb\sentencepiece_model.pb.cc:396:const ::PROTOBUF_NAMESPACE_ID::internal::LazyString TrainerSpec::_i_give_permission_to_break_this_code_default_eos_piece_{{{"</s>", 4}}, {nullptr}};
src\builtin_pb\sentencepiece_model.pb.cc:397:const ::PROTOBUF_NAMESPACE_ID::internal::LazyString TrainerSpec::_i_give_permission_to_break_this_code_default_pad_piece_{{{"<pad>", 5}}, {nullptr}};
src\builtin_pb\sentencepiece_model.pb.cc:398:const ::PROTOBUF_NAMESPACE_ID::internal::LazyString TrainerSpec::_i_give_permission_to_break_this_code_default_unk_surface_{{{" \342\201\207 ", 5}}, {nullptr}};
src\builtin_pb\sentencepiece_model.pb.h:958:  static const ::PROTOBUF_NAMESPACE_ID::internal::LazyString _i_give_permission_to_break_this_code_default_unk_surface_;
src\builtin_pb\sentencepiece_model.pb.h:960:  static const ::PROTOBUF_NAMESPACE_ID::internal::LazyString _i_give_permission_to_break_this_code_default_unk_piece_;
src\builtin_pb\sentencepiece_model.pb.h:962:  static const ::PROTOBUF_NAMESPACE_ID::internal::LazyString _i_give_permission_to_break_this_code_default_bos_piece_;
src\builtin_pb\sentencepiece_model.pb.h:964:  static const ::PROTOBUF_NAMESPACE_ID::internal::LazyString _i_give_permission_to_break_this_code_default_eos_piece_;
src\builtin_pb\sentencepiece_model.pb.h:966:  static const ::PROTOBUF_NAMESPACE_ID::internal::LazyString _i_give_permission_to_break_this_code_default_pad_piece_;
third_party\protobuf-lite\arenastring.cc:50:const std::string& LazyString::Init() const {
third_party\protobuf-lite\arenastring.cc:120:std::string* ArenaStringPtr::Mutable(const LazyString& default_value,
third_party\protobuf-lite\arenastring.cc:241:void ArenaStringPtr::ClearToDefault(const LazyString& default_value,
third_party\protobuf-lite\google\protobuf\arenastring.h:56:class PROTOBUF_EXPORT LazyString {
third_party\protobuf-lite\google\protobuf\arenastring.h:58:  // We explicitly make LazyString an aggregate so that MSVC can do constant
third_party\protobuf-lite\google\protobuf\arenastring.h:148://   `const LazyString&` for it.
third_party\protobuf-lite\google\protobuf\arenastring.h:206:  std::string* Mutable(const LazyString& default_value, ::google::protobuf::Arena* arena);
third_party\protobuf-lite\google\protobuf\arenastring.h:247:  void ClearToDefault(const LazyString& default_value, ::google::protobuf::Arena* arena);
third_party\protobuf-lite\google\protobuf\arenastring.h:295:  // Variadic to support 0 args for EmptyDefault and 1 arg for LazyString.
```

</details>

**Comment by h-vetinari** [comment]
The compilers might get it, but I'm having trouble wrapping my head around how three values (e.g. `{{{"<unk>", 5}}, {nullptr}}`) are supposed to initialize what looks like 5 values (4 if counting the union as one);
```C++
 public:
  struct InitValue {
    const char* ptr;
    size_t size;
  };
  // We keep a union of the initialization value and the std::string to save on
  // space. We don't need the string array after Init() is done.
  union {
    mutable InitValue init_value_;
    alignas(std::string) mutable char string_buf_[sizeof(std::string)];
  };
  mutable std::atomic<const std::string*> inited_;
```

**Comment by h-vetinari** [comment]
My god, I did not plan to get so deep into initializers... Anonymous unions, aggregate initialization (which has special rules for static members), union initialization rules etc... 😅

**Comment by h-vetinari** [comment]
damn, that it is one deep rabbit hole... I managed to get rid of the previous errors of
```
error LNK2019: unresolved external symbol "private: static class google::protobuf::internal::LazyString const sentencepiece::TrainerSpec::_i_give_permission_to_break_this_code_default_unk_piece_"
```
etc. (by moving the initializer to the header, getting a fortuitous clang warning on osx-arm - msvc's warning was useless - and then turning it to constexpr).

Nowe there's still external symbol errors with missing virtual function tables
```
  Auto build dll exports
     Creating library D:/bld/sentencepiece-split_1644334940326/work/build/src/Release/sentencepiece_train_import.lib and object D:/bld/sentencepiece-split_1644334940326/work/build/src/Release/sentencepiece_train_import.exp
trainer_interface.obj : error LNK2019: unresolved external symbol "const sentencepiece::ModelProto::`vftable'" (??_7ModelProto@sentencepiece@@6B@) referenced in function "private: class sentencepiece::util::Status __cdecl sentencepiece::TrainerInterface::SaveModel(class absl::string_view)const " (?SaveModel@TrainerInterface@sentencepiece@@AEBA?AVStatus@util@2@Vstring_view@absl@@@Z) [D:\bld\sentencepiece-split_1644334940326\work\build\src\sentencepiece_train.vcxproj]
unigram_model_trainer.obj : error LNK2001: unresolved external symbol "const sentencepiece::ModelProto::`vftable'" (??_7ModelProto@sentencepiece@@6B@) [D:\bld\sentencepiece-split_1644334940326\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2001: unresolved external symbol "const sentencepiece::ModelProto::`vftable'" (??_7ModelProto@sentencepiece@@6B@) [D:\bld\sentencepiece-split_1644334940326\work\build\src\sentencepiece_train.vcxproj]
unigram_model_trainer.obj : error LNK2019: unresolved external symbol "class sentencepiece::TrainerSpecDefaultTypeInternal sentencepiece::_TrainerSpec_default_instance_" (?_TrainerSpec_default_instance_@sentencepiece@@3VTrainerSpecDefaultTypeInternal@1@A) referenced in function "public: virtual bool __cdecl sentencepiece::ModelInterface::ByteFallbackEnabled(void)const " (?ByteFallbackEnabled@ModelInterface@sentencepiece@@UEBA_NXZ) [D:\bld\sentencepiece-split_1644334940326\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2019: unresolved external symbol "const sentencepiece::TrainerSpec::`vftable'" (??_7TrainerSpec@sentencepiece@@6B@) referenced in function "public: static class sentencepiece::util::Status __cdecl sentencepiece::SentencePieceTrainer::Train(class std::unordered_map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::hash<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,struct std::equal_to<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &,class sentencepiece::SentenceIterator *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?Train@SentencePieceTrainer@sentencepiece@@SA?AVStatus@util@2@AEBV?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@std@@PEAVSentenceIterator@2@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@6@@Z) [D:\bld\sentencepiece-split_1644334940326\work\build\src\sentencepiece_train.vcxproj]
sentencepiece_trainer.obj : error LNK2019: unresolved external symbol "const sentencepiece::NormalizerSpec::`vftable'" (??_7NormalizerSpec@sentencepiece@@6B@) referenced in function "public: static class sentencepiece::NormalizerSpec __cdecl sentencepiece::SentencePieceTrainer::GetNormalizerSpec(class absl::string_view)" (?GetNormalizerSpec@SentencePieceTrainer@sentencepiece@@SA?AVNormalizerSpec@2@Vstring_view@absl@@@Z) [D:\bld\sentencepiece-split_1644334940326\work\build\src\sentencepiece_train.vcxproj]
D:\bld\sentencepiece-split_1644334940326\work\build\src\Release\sentencepiece_train.dll : fatal error LNK1120: 4 unresolved externals [D:\bld\sentencepiece-split_1644334940326\work\build\src\sentencepiece_train.vcxproj]
```

Based on some googling, this [answer](https://stackoverflow.com/a/57504289) gives some good explanation/context. I even found a method without a body anywhere in the sources, but even adding that hasn't fixed it.

**Comment by h-vetinari** [comment]
@xhochy

OK, making some more headway after managing to patch the protoc-generated sources, and figuring out that ~the cake~ `SPM_USE_EXTERNAL_ABSL` is a lie - i.e. there were lots of unconditional `#include "third_party/absl/...` everywhere.

After several false starts and finally placing the sentencepiece-specific glue code that pretends to be third-party code in the actual sources (I'm gonna try to upstream this eventually), I'm now back to green on linux/osx (though OSX was missing some symbols with the current abseil baseline, but passes with the newest one for which the migration just started...).

On windows, there was also a new set of errors (pervious compilation errors were most likely due to the above inclusion collision shenanigans), down to "only" linker errors, because protoc (and/or CMake) somewhere set `sentencepiece.pb.obj` to use static linking against the MSVC MultiThread runtime (despite `-DPROTOBUF_USE_DLLS` and any other seemingly relevant option I could find). This took some further head-banging-against-the-wall, but seems to have been solved with an ugly CMake hack (marginally less disgusting than directly patching the generated `sentencepiece.vcxproj`)...

In any case, I'm now thinking that the remaining errors are because abseil on windows isn't compiled with `BUILD_SHARED_LIBS` from what I can [tell](https://github.com/conda-forge/abseil-cpp-feedstock/blob/master/recipe/bld.bat). I looked at the first error and doing
```
#include "absl/strings/numbers.h"
[...]
int main() {
    int32 freq = 1;
    CHECK_OR_RETURN(absl::SimpleAtoi(some_string, &freq)
}
```
fails with 
```
error LNK2019: unresolved external symbol "bool __cdecl absl::lts_20211102::numbers_internal::safe_strto32_base(class std::basic_string_view<char,struct std::char_traits<char> >,int *,int)" (?safe_strto32_base@numbers_internal@lts_20211102@absl@@YA_NV?$basic_string_view@DU?$char_traits@D@std@@@std@@PEAHH@Z) referenced in function "bool __cdecl absl::lts_20211102::SimpleAtoi<int>(class std::basic_string_view<char,struct std::char_traits<char> >,int *)" (??$SimpleAtoi@H@lts_20211102@absl@@YA_NV?$basic_string_view@DU?$char_traits@D@std@@@std@@PEAH@Z) [D:\bld\sentencepiece-split_1645439189158\work\build\src\sentencepiece.vcxproj]
```
even though that's clearly part of the public [API](https://github.com/abseil/abseil-cpp/blob/20211102.0/absl/strings/numbers.h#L268-L270), and the internal symbol shouldn't concern us. I'll try to raise a PR on the abseil-feedstock and we can discuss there...

**Comment by h-vetinari** [comment]
With the changes in `abseil_dev`, I'm down to _one_ missing symbol:
```
private: static void const * const absl::lts_20211102::hash_internal::MixingHashState::kSeed
```

This one is hard to make constexpr, because it dereferences an uninitialized pointer to get some random value...

**Pull request closed without merging**
