### PR TITLE
add win build

### PR DESCRIPTION
**Pull request by oblute**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by oblute** [comment]
@conda-forge-admin, please rerender

**Comment by oblute** [comment]
@conda-forge-admin, please rerender

**Comment by oblute** [comment]
@conda-forge-admin, please rerender

**Comment by setu4993** [comment]
Thanks for taking this on, @oblute! Can you please @ me when you think it is ready for merging?

**Comment by oblute** [comment]
@setu4993 highly unsure i will succeed here, but will do!

**Comment by setu4993** [comment]
Good luck @oblute! Are you familiar with building C++ conda packages for MacOS (I am not)? If yes, and would like to take a stab at adding MacOS support, would be great.

I tried when submitting this for initial feedstock and again a couple months ago (#5), but would appreciate any help.

**Comment by setu4993** [comment]
Closing in favor of #9.

**Pull request closed without merging**
