### PR TITLE
add windows build

### PR DESCRIPTION
**Pull request by rluria14**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rluria14** [comment]
@setu4993 working build for windows

**Comment by rluria14** [comment]
@oblute, @ndmaxar, and myself have also been added as maintainers

**Comment by setu4993** [comment]
Thanks @rluria14! This is great! Once @ndmaxar confirms they want to be added as a maintainer, will merge this in.

**Comment by setu4993** [comment]
Secondly, we still don't have this feedstock built MacOS, if you are familiar with the MacOS build process, would appreciate a PR on that as well :).

**Pull request merged**
